import { writeFileSync } from "fs";
import { resolve } from "path";
import { describe, it } from "vitest";
import {
  healthRumorCase,
  politicalRumorCase,
  techRumorCase,
} from "../data/rumorCases";
import { aggregateInferences } from "./inferenceLicense";
import {
  scoreFactDeskDraft,
  writeFactDeskFromCase,
} from "./factDeskWriter";
import { composeReport } from "./reportComposer";
import { gradeAll } from "./graderRules";

/**
 * One-shot dump for product review (not a unit assertion gate).
 * Writes docs/DEMO_FACTDESK_3CASES.md at repo root docs/.
 */
describe("dump fact-desk demo report", () => {
  it("writes DEMO_FACTDESK_3CASES.md", () => {
    const cases = [
      ["political-policy-rumor", politicalRumorCase],
      ["health-overnight-vegetables", healthRumorCase],
      ["tech-5g-radiation", techRumorCase],
    ] as const;

    const lines: string[] = [
      "# Demo: Prompt A+F on 3 rumor cases",
      "",
      "> Generated by `factDeskWriter` + `composeReport`.",
      "> Rubric pass if score ≥ 10/12.",
      "",
    ];

    for (const [id, c] of cases) {
      const g = gradeAll(c.candidates, c.subclaims);
      const lic = aggregateInferences(g, c.subclaims);
      const desk = writeFactDeskFromCase(c, g, lic, {
        nextEvidenceNeeded: c.routes.flatMap((r) => r.neededEvidence).slice(0, 3),
      });
      const report = composeReport(c, g);
      const score = scoreFactDeskDraft(desk, c.originalClaim);
      const chips = (report.attentionGuidance?.spans ?? [])
        .filter((s) => (s.sources?.length ?? 0) > 0)
        .map(
          (s) =>
            `${s.text.slice(0, 28)}… → ${(s.sources ?? []).map((x) => x.title).join(" / ")}`,
        );

      lines.push(`## ${id}`, "");
      lines.push(`**原说法：** ${c.originalClaim}`, "");
      lines.push(
        `**评分：** ${score.total}/12 ${score.pass ? "PASS" : "FAIL"} \`${JSON.stringify(score.details)}\``,
        "",
      );
      lines.push("**结论 lede（Prompt A+F）：**", "");
      lines.push(`> ${report.rewrittenClaim.cautious}`, "");
      lines.push("**对外短句：**", "");
      lines.push(`> ${report.rewrittenClaim.publicFacing}`, "");
      lines.push("**可以说：**");
      for (const x of desk.canSay.slice(0, 4)) lines.push(`- ${x}`);
      lines.push("", "**不能说：**");
      for (const x of desk.cannotSay.slice(0, 4)) lines.push(`- ${x}`);
      lines.push("", "**来源芯片（B）样本：**");
      if (chips.length === 0) lines.push("- （本轮未挂上芯片）");
      else for (const x of chips.slice(0, 4)) lines.push(`- ${x}`);
      lines.push("", "---", "");
    }

    const out = resolve(__dirname, "../../../docs/DEMO_FACTDESK_3CASES.md");
    writeFileSync(out, lines.join("\n"), "utf8");
  });
});
