/**
 * Chrome language for the process desk. Verdict memo stays in the claim's language.
 * Default 中文. Persist in localStorage. Names are native (中文 / English).
 */

export type UiLang = "zh" | "en";

export const UI_LANG_KEY = "rhg.uiLang";

export type UiCopy = {
  runProcess: string;
  thinking: string;
  thoughtDeeply: string;
  search: string;
  searching: string;
  visit: string;
  visiting: string;
  boardCreated: string;
  hideBoard: string;
  viewBoard: string;
  taskBoard: string;
  planning: string;
  checking: string;
  followUp: string;
  followLiveTitle: string;
  followDoneTitle: string;
  send: string;
  sendUnavailable: string;
  disclaimer: string;
  stop: string;
  again: string;
  replay: string;
  change: string;
  langGroup: string;
  todoTitle: string;
  stepsComplete: string;
  stepsUnit: string;
};

export const UI_COPY: Record<UiLang, UiCopy> = {
  zh: {
    runProcess: "核查过程",
    thinking: "思考中…",
    thoughtDeeply: "深入思考",
    search: "检索网页",
    searching: "正在检索",
    visit: "打开页面",
    visiting: "正在打开",
    boardCreated: "已创建任务板",
    hideBoard: "收起任务板",
    viewBoard: "查看任务板",
    taskBoard: "任务板",
    planning: "正在规划核查路径…",
    checking: "核查进行中",
    followUp: "再问一句…",
    followLiveTitle: "这一轮不能追问。要停下来请点停止。",
    followDoneTitle: "再问一句，继续查这条。要换问题请点再查一条。",
    send: "发送",
    sendUnavailable: "发送不可用",
    disclaimer: "内容由红鲱鱼与枪生成。请自行判断。",
    stop: "停止",
    again: "再查一条",
    replay: "再看一遍",
    change: "换一条",
    langGroup: "界面语言",
    todoTitle: "核查计划",
    stepsComplete: "完成",
    stepsUnit: "步",
  },
  en: {
    runProcess: "Run process",
    thinking: "thinking…",
    thoughtDeeply: "Thought deeply",
    search: "Search web",
    searching: "Searching web",
    visit: "Visit page",
    visiting: "Visiting page",
    boardCreated: "Task board created",
    hideBoard: "Hide board",
    viewBoard: "View board",
    taskBoard: "Task board",
    planning: "Planning the check…",
    checking: "Checking",
    followUp: "Ask a follow-up…",
    followLiveTitle: "This round cannot take a follow-up. Tap Stop to quit.",
    followDoneTitle: "Ask a follow-up on this claim. Tap Check another for a new one.",
    send: "Send",
    sendUnavailable: "Send unavailable",
    disclaimer: "The content is generated by 红鲱鱼与枪. Critical review is advised.",
    stop: "Stop",
    again: "Check another",
    replay: "Replay",
    change: "New claim",
    langGroup: "Language",
    todoTitle: "Investigation plan",
    stepsComplete: "complete",
    stepsUnit: "steps",
  },
};

const listeners = new Set<() => void>();

function asLang(value: string | null | undefined): UiLang | null {
  if (value === "zh" || value === "en") return value;
  return null;
}

export function readUiLang(): UiLang {
  if (typeof window === "undefined") return "zh";
  const stored = asLang(window.localStorage.getItem(UI_LANG_KEY));
  if (stored) return stored;
  return asLang(new URLSearchParams(window.location.search).get("lang")) ?? "zh";
}

export function applyUiLang(lang: UiLang): void {
  if (typeof document !== "undefined") {
    document.documentElement.lang = lang === "en" ? "en" : "zh-CN";
  }
}

export function setUiLang(lang: UiLang): void {
  if (typeof window !== "undefined") {
    window.localStorage.setItem(UI_LANG_KEY, lang);
  }
  applyUiLang(lang);
  listeners.forEach((fn) => fn());
}

export function subscribeUiLang(fn: () => void): () => void {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}

export function processStepLabel(
  step: { kind: string; status: string; ticker?: boolean },
  copy: UiCopy
): string {
  if (step.kind === "thought") {
    return step.ticker && step.status === "loading" ? copy.thinking : copy.thoughtDeeply;
  }
  if (step.kind === "board") return copy.boardCreated;
  if (step.kind === "search") return step.status === "loading" ? copy.searching : copy.search;
  if (step.kind === "visit") return step.status === "loading" ? copy.visiting : copy.visit;
  return copy.runProcess;
}

export function stopChromeLabel(
  live: boolean,
  stopLabel: string | undefined,
  copy: UiCopy
): string {
  if (live) {
    if (stopLabel === "换一条") return copy.change;
    return copy.stop;
  }
  if (stopLabel === "再看一遍") return copy.replay;
  if (stopLabel === "换一条") return copy.change;
  if (stopLabel && stopLabel !== "停止" && stopLabel !== "再查一条") return stopLabel;
  return copy.again;
}
