/**
 * EvidenceMatrix 演示用 Mock 数据
 * 模拟 "扬州" 相关核查的交叉验证结果
 */

import type { EvidenceConsensusReport, MultiSearchJob } from "../../lib/schemas";

export const mockConsensusReport: EvidenceConsensusReport = {
  consensusId: "demo-consensus-001",
  timestamp: Date.now(),
  overallStats: {
    totalPropositions: 3,
    readyForReasoning: 1,
    doubtful: 0,
    needsManualReview: 2,
    totalIndependentSources: 10,
    totalDuplicateSources: 3,
    counterEvidenceSearchesPerformed: 2,
  },
  propositionResults: [
    {
      propositionId: "prop-1",
      propositionText: "扬州近日出现不明飞行物，多人目击并拍摄视频",
      status: "需人工复核",
      statusReason: "多源报道存在，但缺乏权威信源确认",
      evidenceIndependence: {
        totalSources: 5,
        independentSources: 4,
        duplicateSources: 1,
        independenceScore: 73,
        reasoning: "4个独立来源，1个为转载",
      },
      sourceTierDistribution: {
        government: 0,
        academic: 0,
        media: 2,
        selfMedia: 2,
        forum: 1,
        unknown: 0,
        highestTierFound: "media",
      },
      counterEvidenceCoverage: {
        counterSearchPerformed: true,
        counterEvidenceFound: false,
        counterEvidenceCount: 0,
        counterEvidenceSources: [],
        verdict: "暂未发现反证",
      },
      providerResults: [
        {
          provider: "360_search",
          status: "completed",
          sourceCount: 3,
          relevantSources: 2,
          supportsProposition: true,
          contradictsProposition: false,
          topSourceUrl: "https://news.example.com/yangzhou-ufo",
        },
        {
          provider: "any_search",
          status: "completed",
          sourceCount: 2,
          relevantSources: 1,
          supportsProposition: true,
          contradictsProposition: false,
          topSourceUrl: "https://social.example.com/post/123",
        },
        {
          provider: "metaso_search",
          status: "completed",
          sourceCount: 4,
          relevantSources: 3,
          supportsProposition: true,
          contradictsProposition: false,
          topSourceUrl: "https://blog.example.com/yangzhou-sky",
        },
        {
          provider: "tavily_search",
          status: "failed",
          sourceCount: 0,
          relevantSources: 0,
          supportsProposition: null,
          contradictsProposition: null,
          topSourceUrl: "",
        },
        {
          provider: "exa_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 1,
          supportsProposition: true,
          contradictsProposition: false,
          topSourceUrl: "https://archive.example.com/yangzhou-2024",
        },
      ],
      independentSources: [],
      meetsMinimumCriteria: {
        criteria1_minProviders: true,
        criteria2_hasHighTierOrOriginal: true,
        criteria3_counterSearchDone: true,
        criteria4_duplicatesCountedOnce: true,
        allMet: true,
      },
    },
    {
      propositionId: "prop-2",
      propositionText: "扬州官方已确认该不明飞行物为无人机测试",
      status: "需人工复核",
      statusReason: "官方未发布正式声明，网传截图来源不明",
      evidenceIndependence: {
        totalSources: 3,
        independentSources: 2,
        duplicateSources: 1,
        independenceScore: 58,
        reasoning: "2个独立来源，均非官方渠道",
      },
      sourceTierDistribution: {
        government: 0,
        academic: 0,
        media: 1,
        selfMedia: 1,
        forum: 1,
        unknown: 0,
        highestTierFound: "media",
      },
      counterEvidenceCoverage: {
        counterSearchPerformed: true,
        counterEvidenceFound: false,
        counterEvidenceCount: 0,
        counterEvidenceSources: [],
        verdict: "反证检索未执行",
      },
      providerResults: [
        {
          provider: "360_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 1,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://factcheck.example.com/yangzhou",
        },
        {
          provider: "any_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 0,
          supportsProposition: false,
          contradictsProposition: false,
          topSourceUrl: "",
        },
        {
          provider: "metaso_search",
          status: "completed",
          sourceCount: 2,
          relevantSources: 1,
          supportsProposition: null,
          contradictsProposition: null,
          topSourceUrl: "https://question.example.com/yangzhou-drone",
        },
        {
          provider: "tavily_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 1,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://news.example.com/no-official",
        },
        {
          provider: "exa_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 0,
          supportsProposition: false,
          contradictsProposition: false,
          topSourceUrl: "",
        },
      ],
      independentSources: [],
      meetsMinimumCriteria: {
        criteria1_minProviders: true,
        criteria2_hasHighTierOrOriginal: false,
        criteria3_counterSearchDone: false,
        criteria4_duplicatesCountedOnce: true,
        allMet: false,
      },
    },
    {
      propositionId: "prop-3",
      propositionText: "该事件导致扬州机场临时关闭两小时",
      status: "可进入推理",
      statusReason: "360 Search 和 Metaso 均未找到机场关闭相关报道，多个来源直接否认",
      evidenceIndependence: {
        totalSources: 4,
        independentSources: 4,
        duplicateSources: 0,
        independenceScore: 85,
        reasoning: "4个独立来源均否认该说法",
      },
      sourceTierDistribution: {
        government: 0,
        academic: 0,
        media: 2,
        selfMedia: 1,
        forum: 1,
        unknown: 0,
        highestTierFound: "media",
      },
      counterEvidenceCoverage: {
        counterSearchPerformed: true,
        counterEvidenceFound: true,
        counterEvidenceCount: 2,
        counterEvidenceSources: [
          "https://flight.example.com/yangzhou-schedule",
          "https://airport.example.com/notice",
        ],
        verdict: "反证已覆盖",
      },
      providerResults: [
        {
          provider: "360_search",
          status: "completed",
          sourceCount: 2,
          relevantSources: 2,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://flight.example.com/yangzhou-schedule",
        },
        {
          provider: "any_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 1,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://airport.example.com/notice",
        },
        {
          provider: "metaso_search",
          status: "completed",
          sourceCount: 2,
          relevantSources: 2,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://travel.example.com/yangzhou-normal",
        },
        {
          provider: "tavily_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 1,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://local.example.com/yangzhou-airport",
        },
        {
          provider: "exa_search",
          status: "completed",
          sourceCount: 1,
          relevantSources: 1,
          supportsProposition: false,
          contradictsProposition: true,
          topSourceUrl: "https://archive.example.com/airport-2024",
        },
      ],
      independentSources: [],
      meetsMinimumCriteria: {
        criteria1_minProviders: true,
        criteria2_hasHighTierOrOriginal: true,
        criteria3_counterSearchDone: true,
        criteria4_duplicatesCountedOnce: true,
        allMet: true,
      },
    },
  ],
};

export const mockSearchJobs: MultiSearchJob[] = [
  {
    jobId: "job-1",
    propositionId: "prop-1",
    propositionText: "扬州近日出现不明飞行物，多人目击并拍摄视频",
    searchTasks: [
      {
        provider: "360_search",
        query: "扬州近日出现不明飞行物 多人目击 视频",
        status: "completed",
      },
    ],
  },
  {
    jobId: "job-2",
    propositionId: "prop-1",
    propositionText: "扬州近日出现不明飞行物，多人目击并拍摄视频",
    searchTasks: [
      {
        provider: "metaso_search",
        query: "扬州近日出现不明飞行物 多人目击 视频",
        status: "completed",
      },
    ],
  },
  {
    jobId: "job-3",
    propositionId: "prop-2",
    propositionText: "扬州官方已确认该不明飞行物为无人机测试",
    searchTasks: [
      {
        provider: "360_search",
        query: "扬州 官方 确认 不明飞行物 无人机测试",
        status: "completed",
      },
    ],
  },
];
