export {
  IMAGE_ORIGIN_NOT_FOUND,
  IMAGE_ORIGIN_NOT_FOUND_ALT,
  applyImageOriginToReport,
  attachImageOriginToBundle,
  countOcrOnlyImageOriginCitations,
  countOcrOnlyImageOriginCitationsInReport,
  isHttpUrl,
  lookupImageOrigin,
  notFoundImageOrigin,
  redactForLog,
  resolveImageOrigin,
  reverseImageVendorAvailable,
  safeLookupImageOrigin,
  visionHintsFromExtraction,
  type ImageOriginLookupInput,
  type ImageOriginResult,
  type ImageOriginStatus,
  type ImagePayload,
  type ReverseImageHit,
  type ReverseImageSearchFn,
  type TextSearchHit,
} from "./imageOrigin.js";
