/**
 * Golden Path 文案：产品语义词（说法 / 命题 / 出处 / 判断 / 追问 / 历史 +
 * 证据语义 支持/反驳/相关/尚缺/争议）。不出现实现层词汇。
 */
import type { UiLang } from "../lib/uiLang";

export const GP_COPY = {
  zh: {
    brandTagline: "RED HERRING & GUN",
    examplesNav: "案例",
    historyLabel: "历史记录",
    accountLabel: "我的",
    signIn: "登录",
    signOut: "退出",
    accountMenu: "账号与设置",
    modelSettings: "模型设置",
    newCheck: "新调查",
    langSwitch: "中/EN",

    inputKicker: "",
    inputHeadlineA: "这句话，",
    inputHeadlineAccent: "站得住吗？",
    inputSub: "放进一句话、一张截图或一个链接。一起查它的出处。",
    inputLabel: "要调查的说法",
    inputPlaceholder: "把你拿不准的说法放进来…",
    inputAttach: "添加图片",
    inputSubmit: "开始调查",
    inputScraping: "正在读取链接…",
    examplesLabel: "你也可以试试这些例子",
    homeCaseTitle: "不只给结论。把依据一起交给你。",
    homeCaseLead: "先看一个案例怎样从一句话，走到可以查验的判断。",
    resultPreviewLabel: "查完大概长这样（示意，不是真结果）",
    resultPreviewAnswer: "不会。维生素 C 顶多略缩短病程，谈不上「治感冒」；普通感冒也很少需要输液。",
    resultPreviewMeta: "有对有错 · 命题 2 条 · 来源 10 条",
    resultPreviewSupportLabel: "支持",
    resultPreviewSupportText: "极端劳累时可能略缩短病程",
    resultPreviewSupportExcerpt: "检索片段（非逐字原文）：可略微缩短感冒病程",
    resultPreviewContradictLabel: "反驳",
    resultPreviewContradictText: "普通人谈不上治疗或预防",
    resultPreviewContradictExcerpt: "检索片段（非逐字原文）：不能预防或治疗普通感冒",
    quotaRemaining: (n: number, kind: "guest" | "user") =>
      kind === "guest" ? `今天还能查 ${n} 次；登录后获得更多次数。` : `今天还能查 ${n} 次。`,
    quotaExhaustedGuest: "今天免费次数用完了，登录后可以继续查。",
    quotaExhaustedUser: "今天的次数用完了，明天再来。",
    serviceChecking: "正在确认调查服务…",
    serviceUnavailable: "调查服务暂时不可用。你的材料还没有提交，请稍后重试。",
    serviceUnknown: "暂时无法确认调查服务状态。你可以继续尝试，若中断请稍后重试。",

    canvasOriginalLabel: "你调查的说法",
    canvasPhasePrefix: "正在调查这个说法",
    canvasClaimsLabel: "这句话被拆成了这些命题",
    canvasEvidenceLabel: "证据与分析",
    claimExpand: "展开",
    claimCollapse: "收起",
    reviewAgain: "重新调查",
    backHome: "返回首页",
    sourceCount: (n: number) => `来源 ${n} 条`,
    claimCount: (n: number) => `命题 ${n} 条`,
    checkedAt: (t: string) => `完成于 ${t}`,
    viewSource: "查看原始来源",
    sourceOpen: "打开原始网页",
    sourceUnreachable: "原始链接目前打不开。这只说明现在访问不到该页，不改变这条材料本身写了什么。",
    sourceRelation: "对这条命题",
    sourceAgainstClaim: "针对命题",
    sourceExcerpt: "检索片段（非逐字原文）",
    sourceFinding: "为什么这条证据重要",
    sourceLimitation: "它不能证明什么",
    sourcePublished: "发表时间",
    sourceRetrieved: "取得时间",
    sourceClose: "关闭",
    gapLabel: "尚缺",
    gapHint: "缺这些材料，所以暂时给不出更强的判断。",
    conflictLabel: "存在争议",
    conflictReasonKnown: "争点在哪",
    conflictReasonUnknown: "双方材料并存，分歧的原因目前还不清楚。",
    boundaryLabel: "边界",
    boundaryHint: "即使证据充分，也不能推出这些。",
    uncertaintyLine: "现有证据还不够，不能下更强的判断。",
    imageOriginTitle: "原图出处",
    imageOriginNotFound: "原图出处未查到",
    imageOriginHint: "截图类调查会额外追查图片最早出现在哪里。",
    interruptedTitle: "这次调查没有完成",
    interruptedBody: "已经查到的命题和材料保留在下面，不会假装有结论。",
    interruptedRetry: "重新调查",
    connectionLost: "与调查服务的连接中断了，这次没有查完。请重试。",
    sameClaimTitle: "这条说法查过",
    sameClaimOpen: "打开旧调查",
    sameClaimRedo: "重新核查",
    cancel: "取消",
    historyEmpty: "还没有查过的说法。",
    historyDrawerTitle: "查过的说法",
    loadingHistory: "正在读取调查历史…",
    historySyncFailed: "账户历史同步失败，暂时无法跨设备找回。",
    oldCaseNotice: (t: string) => `原调查时间：${t}。打开的是当时的记录，没有重新核查。`,
    unknownTime: "旧记录未保存时间",
  },
  en: {
    brandTagline: "RED HERRING & GUN",
    examplesNav: "Examples",
    historyLabel: "History",
    accountLabel: "Me",
    signIn: "Sign in",
    signOut: "Sign out",
    accountMenu: "Account & settings",
    modelSettings: "Model settings",
    newCheck: "New check",
    langSwitch: "中/EN",

    inputKicker: "",
    inputHeadlineA: "Does this claim ",
    inputHeadlineAccent: "hold up?",
    inputSub: "Put in a sentence, a screenshot, or a link. We look up where it came from.",
    inputLabel: "The claim to investigate",
    inputPlaceholder: "Put the claim you are unsure about here…",
    inputAttach: "Add image",
    inputSubmit: "Start investigation",
    inputScraping: "Reading the link…",
    examplesLabel: "Or try one of these",
    homeCaseTitle: "Not just a verdict. The evidence comes with it.",
    homeCaseLead: "See how one sentence becomes a judgment you can inspect.",
    resultPreviewLabel: "What a finished check looks like (illustration, not a real result)",
    resultPreviewAnswer: "No. Vitamin C at best slightly shortens a cold; it does not treat one, and an ordinary cold rarely needs an IV drip.",
    resultPreviewMeta: "Mixed · 2 statements · 10 sources",
    resultPreviewSupportLabel: "Supports",
    resultPreviewSupportText: "May slightly shorten the cold under extreme exertion",
    resultPreviewSupportExcerpt: "Search snippet (not verbatim): may slightly shorten the course of a cold",
    resultPreviewContradictLabel: "Contradicts",
    resultPreviewContradictText: "For ordinary people it neither treats nor prevents",
    resultPreviewContradictExcerpt: "Search snippet (not verbatim): does not prevent or treat the common cold",
    quotaRemaining: (n: number, kind: "guest" | "user") =>
      kind === "guest" ? `${n} free checks left today. Sign in for more.` : `${n} checks left today.`,
    quotaExhaustedGuest: "Free checks are used up for today. Sign in to continue.",
    quotaExhaustedUser: "You've used up today's checks. Come back tomorrow.",
    serviceChecking: "Checking the investigation service…",
    serviceUnavailable: "The investigation service is temporarily unavailable. Nothing was submitted. Please retry later.",
    serviceUnknown: "Can't confirm the service status right now. You can still try.",
    canvasOriginalLabel: "The claim you asked about",
    canvasPhasePrefix: "Investigating this claim",
    canvasClaimsLabel: "This claim was broken into these statements",
    canvasEvidenceLabel: "Evidence & analysis",
    claimExpand: "Expand",
    claimCollapse: "Collapse",
    reviewAgain: "Investigate again",
    backHome: "Back home",
    sourceCount: (n: number) => `${n} sources`,
    claimCount: (n: number) => `${n} statements`,
    checkedAt: (t: string) => `Completed ${t}`,
    viewSource: "Open original source",
    sourceOpen: "Open original page",
    sourceUnreachable: "The original link is currently unreachable. That does not change what this material already recorded.",
    sourceRelation: "For this statement",
    sourceAgainstClaim: "About this statement",
    sourceExcerpt: "Search snippet (not a verbatim quote)",
    sourceFinding: "Why this evidence matters",
    sourceLimitation: "What it cannot prove",
    sourcePublished: "Published",
    sourceRetrieved: "Retrieved",
    sourceClose: "Close",
    gapLabel: "Still missing",
    gapHint: "Without these, a stronger verdict isn't possible yet.",
    conflictLabel: "Conflicting evidence",
    conflictReasonKnown: "Where they disagree",
    conflictReasonUnknown: "Both sides have material; why they disagree is still unclear.",
    boundaryLabel: "Boundaries",
    boundaryHint: "Even with evidence, these do not follow.",
    uncertaintyLine: "The available evidence is not enough for a stronger judgment.",
    imageOriginTitle: "Image origin",
    imageOriginNotFound: "Image origin not found",
    imageOriginHint: "For screenshots we additionally trace where the image first appeared.",
    interruptedTitle: "This investigation didn't finish",
    interruptedBody: "Statements and material gathered so far are kept below. No verdict is pretended.",
    interruptedRetry: "Investigate again",
    connectionLost: "The connection to the investigation service dropped. Please retry.",
    sameClaimTitle: "You've checked this before",
    sameClaimOpen: "Open previous check",
    sameClaimRedo: "Re-check",
    cancel: "Cancel",
    historyEmpty: "No past investigations yet.",
    historyDrawerTitle: "Past investigations",
    loadingHistory: "Loading history…",
    historySyncFailed: "Account history sync failed; saved checks may not sync across devices.",
    oldCaseNotice: (t: string) => `Original check: ${t}. Showing the saved record, not a new check.`,
    unknownTime: "time not saved",
  },
} as const;

export type GpCopy = (typeof GP_COPY)["zh"];

export function gpCopyFor(lang: UiLang): GpCopy {
  return (GP_COPY[lang] ?? GP_COPY.zh) as GpCopy;
}
