import type { AgentTool } from "./types";

export const AGENT_TOOL_REGISTRY: Record<string, AgentTool> = {
  stepfun_vision: {
    id: "stepfun_vision",
    name: "StepFun Vision",
    description: "读取用户上传图片，提取 OCR、截图语义、来源线索和可核查声明。",
    kind: "vision",
    riskLevel: "read",
    requiresAuth: true,
    provider: "stepfun",
  },
  link_fetch: {
    id: "link_fetch",
    name: "Link Fetch",
    description: "抓取用户输入 URL 的正文内容，作为待核查材料而不是事实结论。",
    kind: "fetch",
    riskLevel: "read",
    requiresAuth: false,
    provider: "jina-reader",
  },
  parallel_search: {
    id: "parallel_search",
    name: "Parallel Search",
    description: "同时发起支持、反驳和来源查询，形成多搜索引擎证据包。",
    kind: "search",
    riskLevel: "read",
    requiresAuth: true,
  },
  search360: {
    id: "search360",
    name: "360 Search",
    description: "调用 360 生态搜索获得国产搜索线索。",
    kind: "search",
    riskLevel: "read",
    requiresAuth: true,
    provider: "360",
  },
  anysearch: {
    id: "anysearch",
    name: "AnySearch",
    description: "调用 AnySearch 作为独立搜索源参与交叉验证。",
    kind: "search",
    riskLevel: "read",
    requiresAuth: true,
    provider: "anysearch",
  },
  metaso: {
    id: "metaso",
    name: "Metaso Search",
    description: "调用秘塔搜索作为中文搜索源参与交叉验证。",
    kind: "search",
    riskLevel: "read",
    requiresAuth: true,
    provider: "metaso",
  },
  tavily: {
    id: "tavily",
    name: "Tavily Search",
    description: "调用 Tavily 搜索/研究 API 作为网页证据源。",
    kind: "search",
    riskLevel: "read",
    requiresAuth: true,
    provider: "tavily",
  },
  exa: {
    id: "exa",
    name: "Exa Search",
    description: "调用 Exa 搜索作为语义网页检索源。",
    kind: "search",
    riskLevel: "read",
    requiresAuth: true,
    provider: "exa",
  },
  memory_search: {
    id: "memory_search",
    name: "Agent Memory Search",
    description: "检索相似历史案例、证据条目和有效搜索策略。",
    kind: "memory",
    riskLevel: "read",
    requiresAuth: false,
  },
  memory_write: {
    id: "memory_write",
    name: "Agent Memory Write",
    description: "把完成的案例、证据和搜索策略沉淀到本地 Agent Memory。",
    kind: "memory",
    riskLevel: "write",
    requiresAuth: false,
  },
  fire_confidence: {
    id: "fire_confidence",
    name: "FIRE Confidence",
    description: "按来源、完整度、一致性、时效、权威五维调制置信度。",
    kind: "report",
    riskLevel: "read",
    requiresAuth: false,
  },
  closure_actions: {
    id: "closure_actions",
    name: "Closure Actions",
    description: "生成辟谣卡片、存疑归档、分享表达等闭环动作。",
    kind: "report",
    riskLevel: "publish",
    requiresAuth: false,
  },
};

export function getAgentTool(toolId: string): AgentTool | undefined {
  return AGENT_TOOL_REGISTRY[toolId];
}
