/**
 * Golden Path 文案：产品语义词（说法 / 命题 / 出处 / 判断 / 追问 / 历史 +
 * 证据语义 支持/反驳/相关/尚缺/争议）。不出现实现层词汇。
 */
import type { UiLang } from "../lib/uiLang";

export const GP_COPY = {
  zh: {
    brandTagline: "RED HERRING & GUN",
    examplesNav: "案例",
    historyLabel: "历史记录",
    accountLabel: "我的",
    signIn: "登录",
    signOut: "退出",
    accountMenu: "账号与设置",
    modelSettings: "模型设置",
    newCheck: "新调查",
    langSwitch: "中/EN",

    inputKicker: "",
    inputHeadlineA: "你听到的说法，",
    inputHeadlineAccent: "真的靠谱吗？",
    inputSub: "放进一句话、一张截图或一个链接。一起查它的出处。",
    inputLabel: "要调查的说法",
    inputPlaceholder: "把你拿不准的说法放进来…",
    inputAttach: "添加图片",
    inputSubmit: "开始调查",
    inputScraping: "正在读取链接…",
    linkUnreachableNotice: "链接打不开（可能需要登录），已按你输入的文字继续",
    linkUnreachableVerdict: "链接打不开（可能需要登录），没法从链接里读到要查的说法。",
    examplesLabel: "你也可以试试这些例子",
    homeCasesLabel: "已完成的调查案例",
    homeCaseView: "查看这次调查",
    homeCaseRecheck: "用同一说法重新查",
    homeCaseDate: (t: string) => `调查日期：${t}`,
    copyBriefFailed: "没能复制到剪贴板，请重试。",
    historyScopeGuest: "这些记录只留在这台设备的这个浏览器里。登录后才能跨设备找回。",
    historyScopeAccount: "登录后的记录会进账号历史；这台设备上未登录时查过的，仍只留在本机。",
    shareUnavailableTitle: "分享链接不可用",
    shareUnavailableBody: "这个链接不存在、已被撤销，或已经过期。分享由创建者控制，撤销之后就读不到了。",
    shareCopyFailed: "没能复制链接，请手动选中复制。",
    homeCaseTitle: "不只给结论。把依据一起交给你。",
    homeCaseLead: "先看一个案例怎样从一句话，走到可以查验的判断。",
    resultPreviewLabel: "查完大概长这样（示意，不是真结果）",
    resultPreviewAnswer: "不会。维生素 C 顶多略缩短病程，谈不上「治感冒」；普通感冒也很少需要输液。",
    resultPreviewMeta: "有对有错 · 命题 2 条 · 来源 10 条",
    resultPreviewSupportLabel: "支持",
    resultPreviewSupportText: "极端劳累时可能略缩短病程",
    resultPreviewSupportExcerpt: "检索片段（非逐字原文）：可略微缩短感冒病程",
    resultPreviewContradictLabel: "反驳",
    resultPreviewContradictText: "普通人谈不上治疗或预防",
    resultPreviewContradictExcerpt: "检索片段（非逐字原文）：不能预防或治疗普通感冒",
    quotaRemaining: (n: number, kind: "guest" | "user") =>
      kind === "guest" ? `今天还能查 ${n} 次；登录后获得更多次数。` : `今天还能查 ${n} 次。`,
    quotaExhaustedGuest: "今天免费次数用完了，登录后可以继续查。",
    quotaExhaustedUser: "今天的次数用完了，明天再来。",
    serviceChecking: "正在确认调查服务…",
    serviceUnavailable: "调查服务暂时不可用。你的材料还没有提交，请稍后重试。",
    serviceUnknown: "暂时无法确认调查服务状态。你可以继续尝试，若中断请稍后重试。",

    canvasOriginalLabel: "你调查的说法",
    canvasOriginalInResult: "这句话里",
    canvasPhasePrefix: "正在调查这个说法",
    canvasClaimsLabel: "这句话被拆成了这些命题",
    canvasEvidenceLabel: "依据",
    claimExpand: "展开",
    claimCollapse: "收起",
    reviewAgain: "重新调查",
    backHome: "返回首页",
    sourceCount: (n: number) => `来源 ${n} 条`,
    claimCount: (n: number) => `命题 ${n} 条`,
    checkedAt: (t: string) => `完成于 ${t}`,
    collectedSources: (n: number) => `收集到的来源 ${n}`,
    viewSource: "查看原始来源",
    sourceOpen: "打开原文",
    sourceUnreachable: "原始链接目前打不开。这只说明现在访问不到该页，不改变这条材料本身写了什么。",
    sourceRelation: "对这条命题",
    sourceAgainstClaim: "针对命题",
    sourceExcerpt: "出处原文摘录",
    sourceFinding: "为什么这条证据重要",
    sourceLimitation: "它不能证明什么",
    sourcePublished: "发表时间",
    sourceRetrieved: "取得时间",
    sourceClose: "关闭",
    evidenceKnowledgeMark: (date: string) => (date ? `知识库 · ${date} 已核` : "知识库 · 已核"),
    evidencePriorRoundMark: "依据来自刚才那一轮",
    gapLabel: "尚缺",
    gapHint: "缺这些材料，所以暂时给不出更强的判断。",
    conflictLabel: "存在争议",
    conflictReasonKnown: "争点在哪",
    conflictReasonUnknown: "双方材料并存，分歧的原因目前还不清楚。",
    conflictSideMissing: "材料暂缺",
    conflictSideOther: "其他材料",
    boundaryLabel: "边界",
    boundaryHint: "即使证据充分，也不能推出这些。",
    uncertaintyLine: "现有证据还不够，不能下更强的判断。",
    imageOriginTitle: "原图出处",
    imageOriginNotFound: "原图出处未查到",
    imageOriginHint: "截图类调查会额外追查图片最早出现在哪里。",
    interruptedTitle: "还没有写成总判断",
    interruptedBody: "调查中途停了。已经查到的问题和材料留在下面，不会假装有结论。",
    interruptedPartialTitle: "收束时中途停了",
    interruptedPartialBody: "下面是已经查到的。",
    interruptedHasJudgments: "下面的分条判断是停之前查到的，整句总判断还没写成。",
    overclaimLabel: "过头之处",
    relatedMaterialsToggle: (n: number) => `相关材料 ${n}`,
    interruptedRetry: "重新调查",
    connectionLost: "与调查服务的连接中断了，这次没有查完。请重试。",
    sameClaimTitle: "这条说法查过",
    sameClaimOpen: "打开旧调查",
    sameClaimRedo: "重新核查",
    cancel: "取消",
    historyEmpty: "还没有查过的说法。",
    historyDrawerTitle: "查过的说法",
    loadingHistory: "正在读取调查历史…",
    historySyncFailed: "账户历史同步失败，暂时无法跨设备找回。",
    oldCaseNotice: (t: string) => `原调查时间：${t}。打开的是当时的记录，没有重新核查。`,
    unknownTime: "旧记录未保存时间",
    activityLabel: "调查动态",
    activityUnseen: (n: number) => `有 ${n} 条新发现`,
    activityClaimDecomposed: (text: string) => (text ? `拆出问题：${text}` : "拆出了问题"),
    activitySearchStarted: (query: string) => (query ? `开始查找：${query}` : "开始查找"),
    activitySourceFound: (title: string, domain: string) =>
      title && domain ? `带回材料：${title} · ${domain}` : title ? `带回材料：${title}` : "带回一份材料",
    activitySourceChecked: (title: string, role: string) =>
      role ? `判定这条材料：${role}｜${title || "未标题"}` : `核对材料：${title || "未标题"}`,
    activityEvidenceAssessed: (judgment: string) => (judgment ? `形成判断：${judgment}` : "形成判断"),
    activityJudgmentRevised: (from: string, to: string) =>
      from && to ? `判断改变：${from} → ${to}` : "判断有修正",
    activityConflictDetected: (summary: string) => (summary ? `发现分歧：${summary}` : "发现分歧"),
    activityGapIdentified: (description: string) => (description ? `还缺：${description}` : "还有材料没拿到"),
    activityKnowledgeHit: (date: string) =>
      date ? `命中知识库（${date} 已核），免于本次检索` : "命中知识库（已核），免于本次检索",
    activityPriorRoundReuse: "依据来自刚才那一轮，不再检索已核过的命题",
    activityRunCompleted: "调查完成",
    stopInvestigation: "停止调查",
    stoppingInvestigation: "正在停止",
    stoppedInvestigation: "已停止",
    stoppedBody: "材料与已获得的证据都留在这里。想看完整判断就重新调查一次。",
    stopFailed: "停止请求没有送达，调查可能还在继续。",
    saveLocal: "已保存在此设备",
    saveSyncing: "同步中",
    saveSynced: "已同步",
    saveFailed: "同步失败，重试",
    saveRetry: "重试同步",
    shareTitle: "分享这份结果",
    shareCreate: "创建分享链接",
    shareConfirm: "生成链接",
    shareLoading: "正在看会公开哪些字段…",
    shareCreating: "正在创建…",
    sharePreviewLead: "创建前先确认：公开页会显示下面这些。",
    shareExcluded: "不会公开：账号邮箱、上传的原图、密钥、内部过程与调试记录。",
    shareReady: "链接已创建，可以复制了。",
    shareCopy: "复制链接",
    shareCopied: "已复制",
    shareRevoke: "撤销链接",
    shareRevoked: "这个链接已经撤销，打开它读不到任何正文。",
    shareRevokeNote: "撤销只对之后的访问生效，已经下载走的副本无法收回。",
    shareNeedLogin: "登录后才能创建分享链接。",
    sharePreviewFailed: "没能读到会公开的字段，先不建链接。",
    shareCreateFailed: "链接没有创建成功，请重试。",
    shareRevokeFailed: "撤销没有送达，链接可能仍然可用。",
  },
  en: {
    brandTagline: "RED HERRING & GUN",
    examplesNav: "Examples",
    historyLabel: "History",
    accountLabel: "Me",
    signIn: "Sign in",
    signOut: "Sign out",
    accountMenu: "Account & settings",
    modelSettings: "Model settings",
    newCheck: "New check",
    langSwitch: "中/EN",

    inputKicker: "",
    inputHeadlineA: "Does this claim ",
    inputHeadlineAccent: "hold up?",
    inputSub: "Put in a sentence, a screenshot, or a link. We look up where it came from.",
    inputLabel: "The claim to investigate",
    inputPlaceholder: "Put the claim you are unsure about here…",
    inputAttach: "Add image",
    inputSubmit: "Start investigation",
    inputScraping: "Reading the link…",
    linkUnreachableNotice: "The link cannot be opened (it may need a sign-in). Continuing with the text you typed.",
    linkUnreachableVerdict: "The link cannot be opened (it may need a sign-in), so there is no claim to check from it.",
    examplesLabel: "Or try one of these",
    homeCasesLabel: "Finished investigations",
    homeCaseView: "View this investigation",
    homeCaseRecheck: "Check the same claim again",
    homeCaseDate: (t: string) => `Investigated ${t}`,
    copyBriefFailed: "Could not copy to the clipboard. Try again.",
    historyScopeGuest: "These records stay in this browser on this device. Sign in to find them on another device.",
    historyScopeAccount: "Signed-in records go to your account. Checks made while signed out still stay on this device only.",
    shareUnavailableTitle: "This share link is unavailable",
    shareUnavailableBody: "This link does not exist, was revoked, or has expired. The creator controls the share; after revoke it cannot be read.",
    shareCopyFailed: "Could not copy the link. Select it and copy manually.",
    homeCaseTitle: "Not just a verdict. The evidence comes with it.",
    homeCaseLead: "See how one sentence becomes a judgment you can inspect.",
    resultPreviewLabel: "What a finished check looks like (illustration, not a real result)",
    resultPreviewAnswer: "No. Vitamin C at best slightly shortens a cold; it does not treat one, and an ordinary cold rarely needs an IV drip.",
    resultPreviewMeta: "Mixed · 2 statements · 10 sources",
    resultPreviewSupportLabel: "Supports",
    resultPreviewSupportText: "May slightly shorten the cold under extreme exertion",
    resultPreviewSupportExcerpt: "Search snippet (not verbatim): may slightly shorten the course of a cold",
    resultPreviewContradictLabel: "Contradicts",
    resultPreviewContradictText: "For ordinary people it neither treats nor prevents",
    resultPreviewContradictExcerpt: "Search snippet (not verbatim): does not prevent or treat the common cold",
    quotaRemaining: (n: number, kind: "guest" | "user") =>
      kind === "guest" ? `${n} free checks left today. Sign in for more.` : `${n} checks left today.`,
    quotaExhaustedGuest: "Free checks are used up for today. Sign in to continue.",
    quotaExhaustedUser: "You've used up today's checks. Come back tomorrow.",
    serviceChecking: "Checking the investigation service…",
    serviceUnavailable: "The investigation service is temporarily unavailable. Nothing was submitted. Please retry later.",
    serviceUnknown: "Can't confirm the service status right now. You can still try.",
    canvasOriginalLabel: "The claim you asked about",
    canvasOriginalInResult: "In that sentence",
    canvasPhasePrefix: "Investigating this claim",
    canvasClaimsLabel: "This claim was broken into these statements",
    canvasEvidenceLabel: "Evidence",
    claimExpand: "Expand",
    claimCollapse: "Collapse",
    reviewAgain: "Investigate again",
    backHome: "Back home",
    sourceCount: (n: number) => `${n} sources`,
    claimCount: (n: number) => `${n} statements`,
    checkedAt: (t: string) => `Completed ${t}`,
    collectedSources: (n: number) => `${n} collected sources`,
    viewSource: "Open original source",
    sourceOpen: "Open original",
    sourceUnreachable: "The original link is currently unreachable. That does not change what this material already recorded.",
    sourceRelation: "For this statement",
    sourceAgainstClaim: "About this statement",
    sourceExcerpt: "Authoritative source excerpt",
    sourceFinding: "Why this evidence matters",
    sourceLimitation: "What it cannot prove",
    sourcePublished: "Published",
    sourceRetrieved: "Retrieved",
    sourceClose: "Close",
    evidenceKnowledgeMark: (date: string) =>
      date ? `Knowledge base · verified ${date}` : "Knowledge base · verified",
    evidencePriorRoundMark: "Based on the previous round",
    gapLabel: "Still missing",
    gapHint: "Without these, a stronger verdict isn't possible yet.",
    conflictLabel: "Conflicting evidence",
    conflictReasonKnown: "Where they disagree",
    conflictReasonUnknown: "Both sides have material; why they disagree is still unclear.",
    conflictSideMissing: "Material not available",
    conflictSideOther: "Other material",
    boundaryLabel: "Boundaries",
    boundaryHint: "Even with evidence, these do not follow.",
    uncertaintyLine: "The available evidence is not enough for a stronger judgment.",
    imageOriginTitle: "Image origin",
    imageOriginNotFound: "Image origin not found",
    imageOriginHint: "For screenshots we additionally trace where the image first appeared.",
    interruptedTitle: "No overall judgment yet",
    interruptedBody: "The investigation stopped partway. Questions and material found so far are kept below. No verdict is pretended.",
    interruptedPartialTitle: "It stopped while wrapping up",
    interruptedPartialBody: "What was found is below.",
    interruptedHasJudgments: "The per-statement judgments below were reached before it stopped. There is no overall judgment yet.",
    overclaimLabel: "Where it overreaches",
    relatedMaterialsToggle: (n: number) => `Related material ${n}`,
    interruptedRetry: "Investigate again",
    connectionLost: "The connection to the investigation service dropped. Please retry.",
    sameClaimTitle: "You've checked this before",
    sameClaimOpen: "Open previous check",
    sameClaimRedo: "Re-check",
    cancel: "Cancel",
    historyEmpty: "No past investigations yet.",
    historyDrawerTitle: "Past investigations",
    loadingHistory: "Loading history…",
    historySyncFailed: "Account history sync failed; saved checks may not sync across devices.",
    oldCaseNotice: (t: string) => `Original check: ${t}. Showing the saved record, not a new check.`,
    unknownTime: "time not saved",
    activityLabel: "Live log",
    activityUnseen: (n: number) => `${n} new finding${n === 1 ? "" : "s"}`,
    activityClaimDecomposed: (text: string) => (text ? `Question split out: ${text}` : "Split out the questions"),
    activitySearchStarted: (query: string) => (query ? `Looking for: ${query}` : "Looking for sources"),
    activitySourceFound: (title: string, domain: string) =>
      title && domain ? `Material brought back: ${title} · ${domain}` : title ? `Material brought back: ${title}` : "Material brought back",
    activitySourceChecked: (title: string, role: string) =>
      role ? `This material counts as ${role}: ${title || "untitled"}` : `Checked material: ${title || "untitled"}`,
    activityEvidenceAssessed: (judgment: string) => (judgment ? `Judgment formed: ${judgment}` : "Judgment formed"),
    activityJudgmentRevised: (from: string, to: string) =>
      from && to ? `Judgment revised: ${from} → ${to}` : "Judgment revised",
    activityConflictDetected: (summary: string) => (summary ? `Conflict found: ${summary}` : "Conflict found"),
    activityGapIdentified: (description: string) => (description ? `Still missing: ${description}` : "Something is still missing"),
    activityKnowledgeHit: (date: string) =>
      date
        ? `Reused the knowledge base (verified ${date}) — no search needed this time`
        : "Reused the knowledge base (verified) — no search needed this time",
    activityPriorRoundReuse: "Based on the previous round — already checked statements were not searched again",
    activityRunCompleted: "Investigation complete",
    stopInvestigation: "Stop",
    stoppingInvestigation: "Stopping",
    stoppedInvestigation: "Stopped",
    stoppedBody: "The material and whatever evidence was found are kept here. Start a new check for a full verdict.",
    stopFailed: "The stop request did not reach the server; the investigation may still be running.",
    saveLocal: "Saved on this device",
    saveSyncing: "Syncing",
    saveSynced: "Synced",
    saveFailed: "Sync failed, retry",
    saveRetry: "Retry sync",
    shareTitle: "Share this result",
    shareCreate: "Create share link",
    shareConfirm: "Create link",
    shareLoading: "Checking what would be public…",
    shareCreating: "Creating…",
    sharePreviewLead: "Before creating: the public page shows exactly this.",
    shareExcluded: "Not public: your email, uploaded images, keys, internal process and debug records.",
    shareReady: "Link created — you can copy it now.",
    shareCopy: "Copy link",
    shareCopied: "Copied",
    shareRevoke: "Revoke link",
    shareRevoked: "This link is revoked; opening it shows no content.",
    shareRevokeNote: "Revoking only affects future access; copies already downloaded cannot be recalled.",
    shareNeedLogin: "Sign in first to create a share link.",
    sharePreviewFailed: "Could not read what would be public; no link was created.",
    shareCreateFailed: "The link was not created. Please retry.",
    shareRevokeFailed: "The revoke request did not arrive; the link may still work.",
  },
} as const;

export type GpCopy = (typeof GP_COPY)["zh"];

export function gpCopyFor(lang: UiLang): GpCopy {
  return (GP_COPY[lang] ?? GP_COPY.zh) as GpCopy;
}
